### ISSUE TITLE
Support to lowercase and uppercase conversions

### ISSUE THREAD

**Issue by voyeg3r** [igrek51/regex-rename#1]
I think it would make the tool more powerful if we could use something like:

     regex-rename '(A-Z)-(\d+)(\.jpg)'  '\1\L-\2\3'

The L as a mnemonic to lowercase.

Or it would be a parameter something like `--lower -l`

**Comment by igrek51** [comment]
That's a great idea. I'll take care of that.

**Comment by igrek51** [comment]
Done. 
You can use `\L\1` or `\U\1` syntax for lowercase & uppercase respectively.
Already published in v0.1.2
