### ISSUE TITLE
Alternate options to present results in a method that is easier to differentiate

### ISSUE THREAD

**Issue by luzpaz** [igrek51/regex-rename#7]
Scenario: 

Using `regex-rename --recursive` returns long wrapped lines of text that are hard to decipher due to the multi-nested nature of all the results. 

>[2024-02-14 10:48:25] INFO  matched file: from="unsorted/The Secret Teachings of Plants The Intelligence of the Heart in the Direct Perception of Nature -- Stephen Harrod Buhner -- 2004 -- Inner Traditions _ Bear & Company -- 9781591439820 -- 47990408e83350d01ad2aecf4506756f.epub" to="unsorted/The Secret Teachings of Plants The Intelligence of the Heart in the Direct Perception of Nature -- Stephen Harrod Buhner -- 2004 -- Inner Traditions _ Bear & Company.epub

Note: the above example is in color on the terminal but I wasn't able to replicate it here on github. 

I'd like to offer some ideas for helping to declutter results:

1. Each result returns data and time `[2024-02-14 10:48:25] INFO  matched file:` 
    * Proposal: Add a flag that can disable this option
1. When `matched file: from="path/to/file" to="path/to/renamed-file"`   
    * Proposal: Consider putting each `from=` and `to=` on a separate line to help differentiate them
    * Proposal: Change the color of the `to=""` result to quickly differentiate from `from=""` results

BTW, thank you for all the work on this very cool utility!

**Comment by igrek51** [comment]
That's a good point. I've added `--collate` flag to compare source filenames with the replaced names, so you can differentiate them easily in separate lines.
Then, it is displayed like this:
```
> regex-rename "(\d+)\.(.+)" "\1_Audio.\2" --collate

[2024-02-15 15:23:51] DEBUG matching regular expression pattern to files: pattern=(\d+)\.(.+) replacement=\1_Audio.\2 dry_run=True full_match=False recursive=False padding=None
- from: _1.mp3
    to: 1_Audio.mp3
- from: _2.mp3
    to: 2_Audio.mp3
[2024-02-15 15:23:51] INFO  files matched the pattern: matched=2 mismatched=0
```

```
Options:
...
  --collate                   - Compare source filenames with the replaced names
```
I think that should solve your case.

**Comment by luzpaz** [comment]
Fantastic and Thank you!

**Comment by igrek51** [comment]
It's now released in `1.3.0` version

**Comment by luzpaz** [comment]
@igrek51 any possibility of adding a flag to omit date and time (i.e. `[2024-02-14 10:48:25]`) from results as well ? This could also potentially help folks on smaller screens.

**Comment by igrek51** [comment]
I might do that as well, but this would require changing a library https://github.com/igrek51/nuclear used for logging , in first place.

**Comment by igrek51** [comment]
@luzpaz  Now you can use `--short` flag  to omit date and time in logs to have short and less verbose output. Check out version 1.3.1

**Comment by luzpaz** [comment]
Last request, option to differentiate the color of the `to=""` results from `from=""` :pray: 

I ask because I still encounter some disorientation when trying to make out the difference between long recursed subirectoried paths that linewrap and clutter up the console.

**Comment by igrek51** [comment]
> Last request, option to differentiate the color of the `to=""` results from `from=""` 🙏
> 
> I ask because I still encounter some disorientation when trying to make out the difference between long recursed subirectoried paths that linewrap and clutter up the console.

Actually, I think that seeing it in a red-green "+/-" diff format (like in `git diff` output that we're used to) would be very informative.
